### ISSUE TITLE
GabutDM failed to run on macOS

### ISSUE THREAD

**Issue by fathonix** [gabutakut/gabutdm#197]
I tried building on macOS Monterey 12.4, because there's no great native aria2c front-end that supports macOS and I was gabut. Apparently it built, ran and showed the main window for a split second before it crashed.

```
~/gabutdm/build(master) ❯ meson .. --prefix=/opt/gabutdm
The Meson build system
Version: 0.63.1
Source dir: /Users/aldo/gabutdm
Build dir: /Users/aldo/gabutdm/build
Build type: native build
Project name: com.github.gabutakut.gabutdm
Project version: 1.9.4
C compiler for the host machine: cc (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.5)")
C linker for the host machine: cc ld64 764
Vala compiler for the host machine: valac (valac 0.56.3)
Host machine cpu family: aarch64
Host machine cpu: arm64
Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
Run-time dependency glib-2.0 found: YES 2.72.3
Run-time dependency gtk4 found: YES 4.8.0
Run-time dependency sqlite3 found: YES 3.32.3
Run-time dependency libcanberra found: YES 0.30
Run-time dependency libsoup-3.0 found: YES 3.0.8
Run-time dependency gee-0.8 found: YES 0.20.5
Run-time dependency json-glib-1.0 found: YES 1.6.6
Run-time dependency libqrencode found: YES 4.1.1
Run-time dependency gdk-pixbuf-2.0 found: YES 2.42.9
Run-time dependency cairo found: YES 1.16.0
Run-time dependency libcurl found: YES 7.64.1
Library posix found: YES
Program msgfmt found: YES (/opt/homebrew/bin/msgfmt)
Program msginit found: YES (/opt/homebrew/bin/msginit)
Program msgmerge found: YES (/opt/homebrew/bin/msgmerge)
Program xgettext found: YES (/opt/homebrew/bin/xgettext)
Build targets in project: 10

com.github.gabutakut.gabutdm 1.9.4

  User defined options
    prefix: /opt/gabutdm

Found ninja-1.11.1 at /opt/homebrew/bin/ninja
~/gabutdm/build(master) ❯ ninja
[41/41] Linking target com.github.gabutakut.gabutdm
~/gabutdm/build(master) ❯ sudo ninja install
[0/1] Installing files.
Installing com.github.gabutakut.gabutdm to /opt/gabutdm/bin
Installing data/com.github.gabutakut.gabutdm.desktop to /opt/gabutdm/share/applications
Installing data/com.github.gabutakut.gabutdm.startup.desktop to /opt/gabutdm/etc/xdg/autostart
Installing data/com.github.gabutakut.gabutdm.appdata.xml to /opt/gabutdm/share/metainfo
Installing /Users/aldo/gabutdm/data/icons/16/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/16/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/16x16@2/apps
Installing /Users/aldo/gabutdm/data/icons/24/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/24/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/24x24@2/apps
Installing /Users/aldo/gabutdm/data/icons/32/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/32/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/32x32@2/apps
Installing /Users/aldo/gabutdm/data/icons/48/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/48/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/48x48@2/apps
Installing /Users/aldo/gabutdm/data/icons/64/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/64x64/apps
Installing /Users/aldo/gabutdm/data/icons/64/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/64x64@2/apps
Installing /Users/aldo/gabutdm/data/icons/128/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/128x128/apps
Installing /Users/aldo/gabutdm/data/icons/128/com.github.gabutakut.gabutdm.svg to /opt/gabutdm/share/icons/hicolor/128x128@2/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.active.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.active.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.active.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.active.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.complete.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.complete.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.complete.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.complete.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.error.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.error.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.error.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.error.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.pause.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.pause.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.pause.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.pause.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.magnet.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.magnet.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.magnet.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.magnet.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.waiting.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.waiting.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.waiting.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.waiting.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.auto-symbolic.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.auto-symbolic.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.auto-symbolic.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.auto-symbolic.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.seed.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.seed.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.seed.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.seed.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.metalink.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.metalink.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.metalink.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.metalink.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.torrent.svg to /opt/gabutdm/share/icons/hicolor/16x16/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.torrent.svg to /opt/gabutdm/share/icons/hicolor/24x24/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.torrent.svg to /opt/gabutdm/share/icons/hicolor/32x32/apps
Installing /Users/aldo/gabutdm/data/icons/actions/com.github.gabutakut.gabutdm.torrent.svg to /opt/gabutdm/share/icons/hicolor/48x48/apps
Running custom install script '/opt/homebrew/opt/python@3.10/bin/python3.10 /Users/aldo/gabutdm/meson/post_install.py'
--- stdout ---
Updating desktop database…
Updating icon cache…

--- stderr ---
Traceback (most recent call last):
  File "/Users/aldo/gabutdm/meson/post_install.py", line 14, in <module>
    subprocess.call(['gtk-update-icon-cache', '-qtf', path.join(datadir, 'icons', 'hicolor')])
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gtk-update-icon-cache'

FAILED: install script '/opt/homebrew/opt/python@3.10/bin/python3.10 /Users/aldo/gabutdm/meson/post_install.py' exit code 1, stopped
FAILED: meson-internal__install
/opt/homebrew/Cellar/meson/0.63.1/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
~/gabutdm/build(master) ❯ /opt/gabutdm/bin/com.github.gabutakut.gabutdm

** (gabutdm:11457): WARNING **: 11:17:26.594: Utils.vala:1464: Could not connect to localhost: Connection refused

** (gabutdm:11457): WARNING **: 11:17:26.596: Utils.vala:1464: Could not connect to localhost: Connection refused

** (gabutdm:11457): WARNING **: 11:17:26.598: Utils.vala:1464: Could not connect to localhost: Connection refused

** (gabutdm:11457): WARNING **: 11:17:26.600: Utils.vala:1464: Could not connect to localhost: Connection refused

** (gabutdm:11457): WARNING **: 11:17:26.606: Utils.vala:1464: Could not connect to localhost: Connection refused

** (gabutdm:11457): WARNING **: 11:17:26.608: Utils.vala:1464: Could not connect to localhost: Connection refused

** (gabutdm:11457): WARNING **: 11:17:26.610: Utils.vala:1464: Could not connect to localhost: Connection refused
**
ERROR:../src/Utils.vala:2270:gabut_open_quicklist_co: code should not be reached
Bail out! ERROR:../src/Utils.vala:2270:gabut_open_quicklist_co: code should not be reached
[1]    11223 abort      /opt/gabutdm/bin/com.github.gabutakut.gabutdm
~ ❯ /opt/gabutdm/bin/com.github.gabutakut.gabutdm
**
ERROR:../src/Utils.vala:2270:gabut_open_quicklist_co: code should not be reached
Bail out! ERROR:../src/Utils.vala:2270:gabut_open_quicklist_co: code should not be reached
[1]    23461 abort      /opt/gabutdm/bin/com.github.gabutakut.gabutdm
```

I think the `gtk-update-icon-cache` error is not a big problem, and the `Connection refused` error is only aria2c having not been started. But I can't really infer the last error, as I don't have much time and knowledge about Vala. Do you have any clue regarding the error? Thank you.

**Comment by torikulhabib** [comment]
This code dbus-menu for linux. 
I will put options to disable.
And thanks 👍

**Comment by fathonix** [comment]
Now it works as expected. Thank you very much! Sorry for the late reply though.
<img width="1201" alt="Screen Shot 2022-10-31 at 14 07 36" src="https://user-images.githubusercontent.com/85305733/198951303-be87f5d9-1fba-4927-94b1-29657e1187a1.png">
